; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_port = /dev/cu.usbmodem1201
monitor_port = /dev/cu.usbmodem1201
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_flags = 
	-std=gnu++17
	-DXCLOCK_CX_BIAS=6
	-DXCLOCK_CY_BIAS=5
	-DFULL_REFRESH_INTERVAL=60
build_src_filter = 
	+<*>
	-<render/render_sdl.cpp>
	-<platform/hal_desktop.cpp>
lib_deps = zinggjm/GxEPD2@^1.6.7
