[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
  zinggjm/GxEPD2@^1.6.6
  adafruit/Adafruit GFX Library@^1.12.4

build_flags =
  -std=gnu++17
  -DXCLOCK_CX_BIAS=6
  -DXCLOCK_CY_BIAS=10
  -DFULL_REFRESH_INTERVAL=30
